## Data Profiling

In [18]:
import pandas as pd
import numpy as np
import os

#load datasets
distribution_centers = pd.read_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/thelook_ecommerce.distribution_centers.csv")
events = pd.read_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/thelook_ecommerce.events.csv")
inventory_items = pd.read_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/thelook_ecommerce.inventory_items.csv")
order_items = pd.read_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/thelook_ecommerce.order_items.csv")
orders = pd.read_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/thelook_ecommerce.orders.csv")
products = pd.read_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/thelook_ecommerce.products.csv")
users = pd.read_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/thelook_ecommerce.users.csv")

In [19]:
# data profiling
for name, df in {
    'distribution_centers': distribution_centers,
    'events': events,
    'inventory_items': inventory_items,
    'order_items': order_items,
    'orders': orders,
    'products': products,
    'users': users
}.items():
    print(f"n/{name}")
    print(df.shape)
    display(df.head)

n/distribution_centers
(10, 4)


<bound method NDFrame.head of    id                                         name  latitude  longitude
0   1                                   Memphis TN   35.1174   -89.9711
1   2                                   Chicago IL   41.8369   -87.6847
2   3                                   Houston TX   29.7604   -95.3698
3   4                               Los Angeles CA   34.0500  -118.2500
4   5                               New Orleans LA   29.9500   -90.0667
5   6  Port Authority of New York/New Jersey NY/NJ   40.6340   -73.7834
6   7                              Philadelphia PA   39.9500   -75.1667
7   8                                    Mobile AL   30.6944   -88.0431
8   9                                Charleston SC   32.7833   -79.9333
9  10                                  Savannah GA   32.0167   -81.1167>

n/events
(2420738, 13)


<bound method NDFrame.head of               id  user_id  sequence_number  \
0            551     34.0               12   
1           1730    106.0                6   
2           2093    136.0                3   
3           2190    138.0                3   
4           2882    186.0                4   
...          ...      ...              ...   
2420733  2393753      NaN                1   
2420734  2394984      NaN                1   
2420735  2405817      NaN                1   
2420736  2407546      NaN                1   
2420737  2409643      NaN                1   

                                   session_id               created_at  \
0        3c06e3f2-e8ed-4eb6-b24c-ccec40b8c2e7  2019-08-16 06:37:53 UTC   
1        6d550704-9304-48df-990d-01fdbb676694  2021-02-22 05:56:40 UTC   
2        88457dec-f879-4f47-9585-98067ff94d75  2020-01-15 01:35:00 UTC   
3        2729a4a5-1177-4a13-8419-f5f79f350876  2021-03-02 09:15:42 UTC   
4        0933c284-960e-4f9b-9950-82e2d831c8e4  

n/inventory_items
(487901, 12)


<bound method NDFrame.head of             id  product_id               created_at                  sold_at  \
0        58100       16898  2021-07-13 13:48:37 UTC  2021-07-25 22:59:37 UTC   
1        58101       16898  2021-08-26 05:08:00 UTC                      NaN   
2        60386       16898  2022-04-04 06:22:56 UTC  2022-05-23 07:33:56 UTC   
3        60387       16898  2020-03-15 09:37:00 UTC                      NaN   
4        60388       16898  2020-11-23 14:49:00 UTC                      NaN   
...        ...         ...                      ...                      ...   
487896  376001       14392  2021-02-26 04:00:00 UTC                      NaN   
487897  376002       14392  2021-11-14 01:31:00 UTC                      NaN   
487898  378500       14392  2022-02-22 13:13:01 UTC  2022-04-06 07:34:01 UTC   
487899  378501       14392  2021-12-03 03:32:00 UTC                      NaN   
487900  378502       14392  2022-01-20 03:10:00 UTC                      NaN   

         

n/order_items
(180952, 11)


<bound method NDFrame.head of             id  order_id  user_id  product_id  inventory_item_id      status  \
0        15721     10826     8614       13606              42278     Shipped   
1        19167     13243    10505       13606              51560     Shipped   
2        77007     53140    42340       13606             207367     Shipped   
3       151639    104681    83704       13606             408715     Shipped   
4       170817    117931    94363       13606             460556     Shipped   
...        ...       ...      ...         ...                ...         ...   
180947  126133     87039    69454        3449             339845    Complete   
180948   29532     20413    16195        3449              79513    Returned   
180949   90377     62343    49701        3449             243461  Processing   
180950  121073     83537    66628        3449             326127  Processing   
180951  179920    124196    99421        3449             485103  Processing   

         

n/orders
(124923, 9)


<bound method NDFrame.head of         order_id  user_id      status  gender               created_at  \
0              1        1    Returned    Male  2019-06-04 10:10:00 UTC   
1              2        2  Processing  Female  2022-05-23 14:42:00 UTC   
2              3        3    Complete    Male  2020-06-20 15:09:00 UTC   
3              4        3    Complete    Male  2021-08-23 15:09:00 UTC   
4              5        3     Shipped    Male  2021-07-01 15:09:00 UTC   
...          ...      ...         ...     ...                      ...   
124918    124919    99995  Processing    Male  2021-02-19 05:13:00 UTC   
124919    124920    99996     Shipped  Female  2022-04-17 03:17:00 UTC   
124920    124921    99997  Processing  Female  2022-03-28 17:19:00 UTC   
124921    124922    99998    Complete    Male  2021-03-04 14:20:00 UTC   
124922    124923   100000  Processing    Male  2022-05-02 00:16:00 UTC   

                    returned_at               shipped_at  \
0       2019-06-08 20

n/products
(29120, 9)


<bound method NDFrame.head of           id       cost                       category  \
0      27569  92.652563                           Swim   
1      27445  24.719661                           Swim   
2      27457  15.897600                           Swim   
3      27466  17.850000                           Swim   
4      27481  29.408001                           Swim   
...      ...        ...                            ...   
29115   1993  22.150999  Fashion Hoodies & Sweatshirts   
29116   2062  18.973360  Fashion Hoodies & Sweatshirts   
29117   2308   9.028020  Fashion Hoodies & Sweatshirts   
29118   1852  17.674240  Fashion Hoodies & Sweatshirts   
29119   2296  17.533261  Fashion Hoodies & Sweatshirts   

                                                    name  \
0         2XU Men's Swimmers Compression Long Sleeve Top   
1             TYR Sport Men's Square Leg Short Swim Suit   
2        TYR Sport Men's Solid Durafast Jammer Swim Suit   
3      TYR Sport Men's Swim Short

n/users
(100000, 15)


<bound method NDFrame.head of           id first_name  last_name                       email  age gender  \
0      44262    Michael    Sanchez  michaelsanchez@example.net   48      M   
1      61852      David     Watson     davidwatson@example.org   21      M   
2      82418       Lisa     Rivera      lisarivera@example.net   29      F   
3      23274      Logan     Flores     loganflores@example.com   53      M   
4      30022      Kathy   Peterson   kathypeterson@example.net   23      F   
...      ...        ...        ...                         ...  ...    ...   
99995  86705       Lisa      Moore       lisamoore@example.org   39      F   
99996  97530      Emily  Rodriguez  emilyrodriguez@example.net   18      F   
99997  32319     Ronald       Hart      ronaldhart@example.net   14      M   
99998  35529      Oscar      Davis      oscardavis@example.org   16      M   
99999  52925       Cory       York        coryyork@example.com   26      M   

                                 

In [20]:
# check data types
for name, df in {
    'distribution_centers': distribution_centers,
    'events': events,
    'inventory_items': inventory_items,
    'order_items': order_items,
    'orders': orders,
    'products': products,
    'users': users
}.items():
    print(f"n/{name}")
    display(df.dtypes)

n/distribution_centers


id             int64
name          object
latitude     float64
longitude    float64
dtype: object

n/events


id                   int64
user_id            float64
sequence_number      int64
session_id          object
created_at          object
ip_address          object
city                object
state               object
postal_code         object
browser             object
traffic_source      object
uri                 object
event_type          object
dtype: object

n/inventory_items


id                                  int64
product_id                          int64
created_at                         object
sold_at                            object
cost                              float64
product_category                   object
product_name                       object
product_brand                      object
product_retail_price              float64
product_department                 object
product_sku                        object
product_distribution_center_id      int64
dtype: object

n/order_items


id                     int64
order_id               int64
user_id                int64
product_id             int64
inventory_item_id      int64
status                object
created_at            object
shipped_at            object
delivered_at          object
returned_at           object
sale_price           float64
dtype: object

n/orders


order_id         int64
user_id          int64
status          object
gender          object
created_at      object
returned_at     object
shipped_at      object
delivered_at    object
num_of_item      int64
dtype: object

n/products


id                          int64
cost                      float64
category                   object
name                       object
brand                      object
retail_price              float64
department                 object
sku                        object
distribution_center_id      int64
dtype: object

n/users


id                  int64
first_name         object
last_name          object
email              object
age                 int64
gender             object
state              object
street_address     object
postal_code        object
city               object
country            object
latitude          float64
longitude         float64
traffic_source     object
created_at         object
dtype: object

In [21]:
# check duplicate rows
# check data types
for name, df in {
    'distribution_centers': distribution_centers,
    'events': events,
    'inventory_items': inventory_items,
    'order_items': order_items,
    'orders': orders,
    'products': products,
    'users': users
}.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

distribution_centers: 0 duplicate rows
events: 0 duplicate rows
inventory_items: 0 duplicate rows
order_items: 0 duplicate rows
orders: 0 duplicate rows
products: 0 duplicate rows
users: 0 duplicate rows


## Data Cleaning

In [22]:
import pandas as pd
import numpy as np

# convert from object to datetime
def convert_datetime(df, columns):
    for col in columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')
    return df

users = convert_datetime(
    users,
    ['created_at']
)

events = convert_datetime(
    events,
    ['created_at']
)

inventory_items = convert_datetime(
    inventory_items,
    ['created_at', 'sold_at']
)

order_items = convert_datetime(
    order_items,
    ['created_at', 'shipped_at', 'delivered_at', 'returned_at']
)

orders = convert_datetime(
    orders,
    ['created_at', 'shipped_at', 'delivered_at', 'returned_at']
)

In [23]:
# check data types
for name, df in {
    'events': events,
    'inventory_items': inventory_items,
    'order_items': order_items,
    'orders': orders,
    'users': users
}.items():
    print(f"n/{name}")
    display(df.dtypes)

n/events


id                               int64
user_id                        float64
sequence_number                  int64
session_id                      object
created_at         datetime64[ns, UTC]
ip_address                      object
city                            object
state                           object
postal_code                     object
browser                         object
traffic_source                  object
uri                             object
event_type                      object
dtype: object

n/inventory_items


id                                              int64
product_id                                      int64
created_at                        datetime64[ns, UTC]
sold_at                           datetime64[ns, UTC]
cost                                          float64
product_category                               object
product_name                                   object
product_brand                                  object
product_retail_price                          float64
product_department                             object
product_sku                                    object
product_distribution_center_id                  int64
dtype: object

n/order_items


id                                 int64
order_id                           int64
user_id                            int64
product_id                         int64
inventory_item_id                  int64
status                            object
created_at           datetime64[ns, UTC]
shipped_at           datetime64[ns, UTC]
delivered_at         datetime64[ns, UTC]
returned_at          datetime64[ns, UTC]
sale_price                       float64
dtype: object

n/orders


order_id                      int64
user_id                       int64
status                       object
gender                       object
created_at      datetime64[ns, UTC]
returned_at     datetime64[ns, UTC]
shipped_at      datetime64[ns, UTC]
delivered_at    datetime64[ns, UTC]
num_of_item                   int64
dtype: object

n/users


id                              int64
first_name                     object
last_name                      object
email                          object
age                             int64
gender                         object
state                          object
street_address                 object
postal_code                    object
city                           object
country                        object
latitude                      float64
longitude                     float64
traffic_source                 object
created_at        datetime64[ns, UTC]
dtype: object

## Missing Value Analysis

In [37]:
def missing_summary(df):
    missing_count = df.isnull().sum()
    missing_pct = (missing_count/len(df)) * 100
    
    summary = pd.DataFrame({
        'missing_count': missing_count,
        'missing_pct' : missing_pct
    })
    
    summary = summary [
        summary['missing_count']>0
    ].sort_values(
        by='missing_pct',
        ascending=False
    )
    return summary

for name, df in {
    'distribution_centers': distribution_centers,
    'events': events,
    'inventory_items': inventory_items,
    'order_items': order_items,
    'orders': orders,
    'products': products,
    'users': users
}.items():
    print(f"n/{name}")
    display(missing_summary(df))

n/distribution_centers


,missing_count,missing_pct


n/events


,missing_count,missing_pct
user_id,1124065,46.434806
created_at,32133,1.327405
city,23958,0.989698


n/inventory_items


,missing_count,missing_pct
sold_at,311401,63.824628
created_at,4452,0.912480
product_brand,387,0.079319
product_name,28,0.005739


n/order_items


,missing_count,missing_pct
returned_at,163179,90.178058
delivered_at,119222,65.885981
shipped_at,65911,36.424577
created_at,4452,2.460321


n/orders


,missing_count,missing_pct
returned_at,112645,90.171546
delivered_at,82352,65.922208
shipped_at,45643,36.536907
created_at,3058,2.447908


n/products


,missing_count,missing_pct
brand,24,0.082418
name,2,0.006868


n/users


,missing_count,missing_pct
created_at,2494,2.494
city,962,0.962


In [38]:
orders.groupby('status')[
    ['shipped_at', 'delivered_at', 'returned_at']
].apply(lambda x: x.isnull().mean() * 100)

,shipped_at,delivered_at,returned_at
status,,,
Cancelled,100.000000,100.000000,100.000000
Complete,2.368828,2.368828,100.000000
Processing,100.000000,100.000000,100.000000
Returned,2.322991,2.322991,2.322991
Shipped,2.509694,100.000000,100.000000


In [39]:
inventory_items['sold_at'].isnull().mean()

0.6382462835698226

## Observation

Missing shipping and delivery timestamps are expected for processing and cancelled orders based on business workflow.

~2.4 missing timestamps for complete and returned orders may indicate data synchronization or logging quality issues.

63.8% missing sold_at in inventory_items likely represents unsold inventory still in stock.

Missing user_id in events table likely represents anonymous browsing sessions prior to login. 

## Anomaly Detection

In [40]:
# negative / zero price check
order_items[
    order_items['sale_price'] <=0
]

products[
    (products['retail_price'] <= 0) |
    (products['cost'] <= 0)
]

# no refund / free good / dirty data

,id,cost,category,name,brand,retail_price,department,sku,distribution_center_id


In [41]:
# cost > retail price
products[
    (products['cost'] > products['retail_price'] )
]

# no wrong pricing

,id,cost,category,name,brand,retail_price,department,sku,distribution_center_id


In [42]:
# invalid delivery timeline
# delivered before shipped
invalid_delivery = order_items[
    order_items['delivered_at'] < order_items['shipped_at']
]

invalid_delivery.shape

(0, 11)

In [36]:
#shipped before created
invalid_shipping = order_items[
    order_items['shipped_at'] < order_items['created_at']
]

invalid_shipping.shape

negative_delivery = order_items[
    order_items['delivery_days'] < 0
]
negative_delivery.shape

KeyError: 'delivery_days'

In [ ]:
negative_delivery = order_items[
    order_items['delivery_days'] < 0
]

negative_delivery[
    [
        'created_at',
        'shipped_at',
        'delivered_at',
        'delivery_days'
    ]
].head(10)

In [43]:
# returned before delivered
invalid_return = order_items[
    order_items['returned_at'] < order_items['delivered_at']
]

invalid_return.shape

(0, 11)

In [44]:
#unrealistic delivery time
order_items['delivery_days']=(
    order_items['delivered_at'] - order_items['created_at']
).dt.days

order_items['delivery_days'].describe()

count    61730.000000
mean         2.531038
std          2.222734
min         -4.000000
25%          1.000000
50%          3.000000
75%          4.000000
max          8.000000
Name: delivery_days, dtype: float64

In [45]:
# extreme values
order_items[
    order_items['delivery_days'] > 60
]

,id,order_id,user_id,product_id,inventory_item_id,status,created_at,shipped_at,delivered_at,returned_at,sale_price,delivery_days


In [46]:
order_items[
    order_items['delivery_days'] < 0
]

,id,order_id,user_id,product_id,inventory_item_id,status,created_at,shipped_at,delivered_at,returned_at,sale_price,delivery_days
7,39441,27206,21647,13606,106203,Complete,2021-06-02 03:33:50+00:00,2021-05-30 22:40:00+00:00,2021-05-31 19:41:00+00:00,NaT,2.50,-2.0
20,81584,56273,44825,28557,219699,Complete,2022-04-21 11:23:06+00:00,2022-04-18 07:06:00+00:00,2022-04-20 07:25:00+00:00,NaT,3.25,-2.0
55,164526,113597,90869,28679,443540,Returned,2022-04-22 01:33:33+00:00,2022-04-18 07:14:00+00:00,2022-04-21 16:09:00+00:00,2022-04-21 17:14:00+00:00,3.50,-1.0
196,81143,55963,44575,9303,218535,Complete,2020-12-01 01:06:28+00:00,2020-11-29 17:12:00+00:00,2020-11-29 19:08:00+00:00,NaT,6.00,-2.0
197,84125,58012,46227,9414,226515,Complete,2020-05-10 03:51:10+00:00,2020-05-09 06:39:00+00:00,2020-05-09 19:53:00+00:00,NaT,6.00,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
180769,174172,120227,96150,28394,469556,Complete,2021-08-29 17:10:28+00:00,2021-08-26 22:45:00+00:00,2021-08-27 17:52:00+00:00,NaT,13.93,-2.0
180846,143830,99264,79299,15668,387712,Complete,2021-09-24 08:10:07+00:00,2021-09-22 09:16:00+00:00,2021-09-22 22:43:00+00:00,NaT,8.57,-2.0
180867,107672,74340,59131,15472,290055,Returned,2021-10-22 01:22:11+00:00,2021-10-20 10:59:00+00:00,2021-10-21 12:17:00+00:00,2021-10-21 22:13:00+00:00,6.41,-1.0
180873,44194,30509,24333,6148,118981,Complete,2021-12-15 23:34:52+00:00,2021-12-14 02:20:00+00:00,2021-12-14 08:10:00+00:00,NaT,6.91,-2.0


In [47]:
# age anomaly
users['age'].describe()

count    100000.000000
mean         41.005680
std          17.050124
min          12.000000
25%          26.000000
50%          41.000000
75%          56.000000
max          70.000000
Name: age, dtype: float64

In [48]:
# duplicate business key check
products['sku'].duplicated().sum()

0

In [49]:
users['email'].duplicated().sum()

16083

In [50]:
negative_delivery = order_items[
    order_items['delivery_days'] < 0
]

negative_delivery[
    [
        'created_at',
        'shipped_at',
        'delivered_at',
        'delivery_days'
    ]
].head(10)

,created_at,shipped_at,delivered_at,delivery_days
7,2021-06-02 03:33:50+00:00,2021-05-30 22:40:00+00:00,2021-05-31 19:41:00+00:00,-2.0
20,2022-04-21 11:23:06+00:00,2022-04-18 07:06:00+00:00,2022-04-20 07:25:00+00:00,-2.0
55,2022-04-22 01:33:33+00:00,2022-04-18 07:14:00+00:00,2022-04-21 16:09:00+00:00,-1.0
196,2020-12-01 01:06:28+00:00,2020-11-29 17:12:00+00:00,2020-11-29 19:08:00+00:00,-2.0
197,2020-05-10 03:51:10+00:00,2020-05-09 06:39:00+00:00,2020-05-09 19:53:00+00:00,-1.0
281,2022-05-09 16:12:06+00:00,2022-05-08 06:33:00+00:00,2022-05-08 10:17:00+00:00,-2.0
345,2020-05-02 01:58:34+00:00,2020-04-29 14:50:00+00:00,2020-05-01 07:10:00+00:00,-1.0
352,2022-01-26 04:29:15+00:00,2022-01-22 14:07:00+00:00,2022-01-24 17:05:00+00:00,-2.0
355,2021-10-16 16:13:45+00:00,2021-10-14 00:34:00+00:00,2021-10-14 16:56:00+00:00,-2.0
361,2022-06-07 22:08:16+00:00,2022-06-06 16:09:00+00:00,2022-06-07 19:55:00+00:00,-1.0


## Observation

No negative / 0 pricing values where detected in both order_items and products tables, indicating generally valid pricing records without obvious refund or dirty data issues.

No cases were found where delivered at occurred before shipped_at, and no cases where returned_at occurred before delivered_at, suggesting the delivery lifecycle is mostly logically consistent.

Approsimately 5878 records showed shipped_at earlier than created_at. Further inspection confirmed that many records also contained delivered_at timestamps occurring before order creation timestamps.

Negative delivery_days values ranging from -1 to -4 days indicate potential timestamp inconsistencies, ETL synchronization issues, or data generation anomalies within the dataset.

Since delivered_at should logically occur after order creation, these records are considered invalid for delivery performance analysis and may distort fulfillment KPI calculations.

Recommended Handling:
For downstream analytics and KPI reporting, records with delivery_days < 0 should either:
1. Be excluded from fulfillment-related analysis, or
2. Be corrected only if reliable business rules or source system validation are available.

Delivery duration analysis showed an average delivery time of approximately 2.5 days, with most deliveries completed within 1–4 days, indicating relatively efficient fulfillment operations for valid records.

Customer age distribution appears reasonable, ranging from 12 to 70 years old, with no obvious abnormal age values detected.

No duplicate SKU values were detected in the products table, indicating strong product key uniqueness.

Approximately 16,083 duplicated email values were identified in the users table. This may represent shared/family accounts, synthetic demo data generation, or non-unique customer identities, and should be considered during customer-level analysis.



| Rule                       | Status |
| -------------------------- | ------ |
| delivered_at >= created_at | FAIL   |
| retail_price > 0           | PASS   |
| SKU unique                 | PASS   |
| user email unique          | FAIL   |


In [51]:
# order_items product_id 
order_items[~order_items['product_id'].isin(products['id'])].shape

(0, 12)

In [52]:
# orders user_id 
orders[~orders['user_id'].isin(users['id'])].shape

(0, 9)

In [53]:
#Data Quality Assessment Table
dq_summary = pd.DataFrame({
    'issue_type': [
        'Missing Value',
        'Missing Value',
        'Missing Value',
        'Data Consistency',
        'Data Consistency',
        'Business Key',
        'Business Key'
    ],

    'table': [
        'events',
        'inventory_items',
        'orders',
        'order_items',
        'order_items',
        'products',
        'users'
    ],

    'column': [
        'user_id',
        'sold_at',
        'delivered_at',
        'delivery_days',
        'created_at / shipped_at',
        'sku',
        'email'
    ],

    'issue': [
        '46% missing user_id values',
        '63.8% missing sold_at values',
        '65.9% missing delivered_at values',
        'Negative delivery_days detected',
        'shipped_at earlier than created_at',
        'No duplicated SKU values detected',
        '16,083 duplicated email values detected'
    ],

    'suggested_handling': [
        'Treat as anonymous browsing sessions',
        'Treat as unsold inventory still in stock',
        'Expected for Processing/Shipped orders; validate Complete orders separately',
        'Exclude invalid records from fulfillment KPI analysis',
        'Investigate timestamp consistency before production use',
        'No action required',
        'Use caution for customer-level aggregation and deduplication'
    ]
})

dq_summary

,issue_type,table,column,issue,suggested_handling
0,Missing Value,events,user_id,46% missing user_id values,Treat as anonymous browsing sessions
1,Missing Value,inventory_items,sold_at,63.8% missing sold_at values,Treat as unsold inventory still in stock
2,Missing Value,orders,delivered_at,65.9% missing delivered_at values,Expected for Processing/Shipped orders; valida...
3,Data Consistency,order_items,delivery_days,Negative delivery_days detected,Exclude invalid records from fulfillment KPI a...
4,Data Consistency,order_items,created_at / shipped_at,shipped_at earlier than created_at,Investigate timestamp consistency before produ...
5,Business Key,products,sku,No duplicated SKU values detected,No action required
6,Business Key,users,email,"16,083 duplicated email values detected",Use caution for customer-level aggregation and...


# Schema and Grain Documentation

| Table                  | Grain                               | Primary Key | Main Foreign Keys                                                                                                                | Business Meaning                                                 |
| ---------------------- | ----------------------------------- | ----------- | -------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| `users`                | One row per registered user         | `id`        | N/A                                                                                                                              | Customer profile and acquisition source                          |
| `orders`               | One row per order                   | `order_id`  | `user_id` → `users.id`                                                                                                           | Order-level status, timestamps, and item count                   |
| `order_items`          | One row per item within an order    | `id`        | `order_id` → `orders.order_id`; `user_id` → `users.id`; `product_id` → `products.id`; `inventory_item_id` → `inventory_items.id` | Item-level sales, shipping, delivery, return, and sale price     |
| `products`             | One row per product SKU             | `id`        | `distribution_center_id` → `distribution_centers.id`                                                                             | Product catalog, category, brand, cost, and retail price         |
| `inventory_items`      | One row per physical inventory unit | `id`        | `product_id` → `products.id`; `product_distribution_center_id` → `distribution_centers.id`                                       | Inventory lifecycle, product copy, cost, and sold timestamp      |
| `distribution_centers` | One row per distribution center     | `id`        | N/A                                                                                                                              | Warehouse / fulfillment center location                          |
| `events`               | One row per user/session web event  | `id`        | `user_id` → `users.id` nullable                                                                                                  | Clickstream event data for browsing, cart, and purchase behavior |


## Key Grain Notes

- `orders` is the order-level table. Each row represents one customer order.
- `order_items` is more granular than `orders`. One order can contain multiple order items.
- `products` is the product catalog table. It should be joined to `order_items` using `product_id`.
- `inventory_items` represents physical inventory units and should be joined using `inventory_item_id` when analyzing inventory lifecycle.
- `events` is clickstream-level data and may include anonymous sessions, so `user_id` can be missing.

## Join Warning

When calculating revenue, use `order_items` as the base table because `sale_price` is stored at item level.

Avoid joining `orders` to `order_items` and then counting rows as orders, because this will duplicate orders with multiple items.

Correct logic:
- Revenue = sum of `order_items.sale_price`
- Order count = count distinct `orders.order_id`
- Item count = count rows in `order_items`

## Join Validation

In [54]:
print(orders['order_id'].duplicated().sum())
print(distribution_centers['id'].duplicated().sum())
print(events['id'].duplicated().sum())
print(events['user_id'].duplicated().sum())
print(inventory_items['product_id'].duplicated().sum())
print(order_items['id'].duplicated().sum())
print(order_items['order_id'].duplicated().sum())
print(order_items['user_id'].duplicated().sum())
print(users['id'].duplicated().sum())
print(products['id'].duplicated().sum())

0
0
0
2340844
458847
0
56029
101059
0
0


## Business Rule Validation

| Business Rule                              | Validation                      |
| ------------------------------------------ | ------------------------------- |
| delivered_at should occur after shipped_at | validated with minor violations |
| order_total should be positive             | validated                       |
| product retail_price ≥ cost                | mostly valid                    |
| traffic events may exist without user_id   | business-expected               |


## Save Cleaned Tables

In [56]:
distribution_centers.to_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/clean/distribution_centers_clean.csv", index=False)
events.to_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/clean/events_clean.csv", index=False)
inventory_items.to_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/clean/inventory_items_clean.csv", index=False)
order_items.to_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/clean/order_items_clean.csv", index=False)
orders.to_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/clean/orders_clean.csv", index=False)
products.to_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/clean/products_clean.csv", index=False)
users.to_csv("/Users/chowingchan/Desktop/Project/RAG_TextToSQL/data/clean/users_clean.csv", index=False)